function E3 = E3(a1,b1,phi1,t1,t2)
%E3
%    E3 = E3(A1,B1,PHI1,T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    12-Oct-2023 11:47:24

E3 = t1+t2+pi./2.0+atan2(a1.*sin(phi1),b1.*cos(phi1));
end
