% -------------------------------------------------------------------
%  Generated by MATLAB on 14-Nov-2024 09:32:09
%  MATLAB version: 23.2.0.2599560 (R2023b) Update 8
% -------------------------------------------------------------------
saveVarsMat = load('M1234.mat');

K = struct;

K2 = struct;

T = saveVarsMat.T; % <1x1 table> unsupported class

out = saveVarsMat.out; % <1x1 Simulink.SimulationOutput> unsupported class

clear saveVarsMat;
