function A = R_A(L1,L2,t1,t2)
%R_A
%    A = R_A(L1,L2,T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:06

A = [L2.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))+L1.*cos(t1),L2.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))];
end
