function Aco = R_Aco(X_dd,Xc,Xo,Y_dd,Yo,q1,q1_d,q1_dd)
%R_Aco
%    Aco = R_Aco(X_dd,Xc,Xo,Y_dd,Yo,Q1,Q1_D,Q1_DD)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:07

et1 = cos(q1).*6.123233995736766e-17;
et2 = sin(q1).*(-1.0);
et3 = Yo.*(et1+et2)+Xc.*cos(q1).*1.0+Xo.*cos(q1);
et4 = Yo.*(cos(q1).*6.123233995736766e-17-sin(q1));
et5 = cos(q1).*1.0;
et6 = sin(q1).*6.123233995736766e-17;
et7 = Yo.*(cos(q1)+sin(q1).*6.123233995736766e-17)+Yo.*(et5+et6)+Xc.*sin(q1).*1.0;
et8 = Xo.*sin(q1);
et9 = cos(q1).*6.123233995736766e-17;
et10 = sin(q1).*(-1.0);
et11 = Yo.*(et9+et10)+Xc.*cos(q1).*1.0+Xo.*cos(q1);
et12 = Yo.*(cos(q1).*6.123233995736766e-17-sin(q1));
et13 = cos(q1).*1.0;
et14 = sin(q1).*6.123233995736766e-17;
et15 = Yo.*(cos(q1)+sin(q1).*6.123233995736766e-17)+Yo.*(et13+et14)+Xc.*sin(q1).*1.0;
et16 = Xo.*sin(q1);
Aco = [X_dd-q1_d.^2.*(et11+et12)-q1_dd.*(et15+et16);Y_dd-q1_d.^2.*(et7+et8)+q1_dd.*(et3+et4)];
end
