function A_CM = R_ACM(X_dd,Xo,Y_dd,Yo,q1,q1_d,q1_dd)
%R_ACM
%    A_CM = R_ACM(X_dd,Xo,Y_dd,Yo,Q1,Q1_D,Q1_DD)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:07

mt1 = [X_dd-q1_dd.*(Yo.*(cos(q1)+sin(q1).*6.123233995736766e-17)+Xo.*sin(q1))-q1_d.^2.*(Xo.*cos(q1)+Yo.*(cos(q1).*6.123233995736766e-17-sin(q1)))];
mt2 = [Y_dd+q1_dd.*(Xo.*cos(q1)+Yo.*(cos(q1).*6.123233995736766e-17-sin(q1)))-q1_d.^2.*(Yo.*(cos(q1)+sin(q1).*6.123233995736766e-17)+Xo.*sin(q1))];
A_CM = [mt1;mt2];
end
