function AEQP2 = R_AEQP2(L1,L2,X1,X1_d,X1_dd,X_dd,Xc,Xc_d,Xc_dd,Xo,Y_dd,Yo,q1,q1_d,q1_dd,r,t1,t2,t1_d,t2_d,t1_dd,t2_dd)
%R_AEQP2
%    AEQP2 = R_AEQP2(L1,L2,X1,X1_d,X1_dd,X_dd,Xc,Xc_d,Xc_dd,Xo,Y_dd,Yo,Q1,Q1_D,Q1_DD,R,T1,T2,T1_D,T2_D,T1_DD,T2_DD)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:07

et1 = cos(q1).*6.123233995736766e-17;
et2 = sin(q1).*(-1.0);
et3 = -r.*(cos(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*cos(t2)-sin(t1).*sin(t2))-sin(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*sin(t2)+cos(t2).*sin(t1)))+Yo.*(et1+et2);
et4 = Xc.*cos(q1).*1.0+Xo.*cos(q1)+Yo.*(cos(q1).*6.123233995736766e-17-sin(q1));
et5 = cos(q1).*1.0;
et6 = sin(q1).*6.123233995736766e-17;
et7 = -r.*(cos(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+sin(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*cos(t2)-sin(t1).*sin(t2)))+Yo.*(cos(q1)+sin(q1).*6.123233995736766e-17)+Yo.*(et5+et6);
et8 = Xc.*sin(q1).*1.0+Xo.*sin(q1);
et9 = -Y_dd-q1_dd.*(et3+et4)-Xc_dd.*sin(q1).*1.0-t2_d.*(L2.*t1_d.*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+L2.*t2_d.*(cos(t1).*sin(t2)+cos(t2).*sin(t1)));
et10 = -q1_d.*(Xc_d.*cos(q1).*1.0-q1_d.*(et7+et8))-t1_d.*(t1_d.*(L2.*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+L1.*sin(t1))+L2.*t2_d.*(cos(t1).*sin(t2)+cos(t2).*sin(t1)));
et11 = t1_dd.*(L2.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))+L1.*cos(t1))+L2.*t2_dd.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))-Xc_d.*q1_d.*cos(q1).*1.0;
et12 = cos(q1).*6.123233995736766e-17;
et13 = sin(q1).*(-1.0);
et14 = -r.*(cos(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*cos(t2)-sin(t1).*sin(t2))-sin(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*sin(t2)+cos(t2).*sin(t1)))+Yo.*(et12+et13);
et15 = Xc.*cos(q1).*1.0+Xo.*cos(q1)+Yo.*(cos(q1).*6.123233995736766e-17-sin(q1));
et16 = cos(q1).*1.0;
et17 = sin(q1).*6.123233995736766e-17;
et18 = -r.*(cos(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+sin(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*cos(t2)-sin(t1).*sin(t2)))+Yo.*(cos(q1)+sin(q1).*6.123233995736766e-17)+Yo.*(et16+et17);
et19 = Xc.*sin(q1).*1.0+Xo.*sin(q1);
et20 = -X_dd-t1_dd.*(L2.*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+L1.*sin(t1))+q1_d.*(q1_d.*(et14+et15)+Xc_d.*sin(q1).*1.0);
et21 = Xc_dd.*cos(q1).*(-1.0)-t2_d.*(L2.*t1_d.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))+L2.*t2_d.*(cos(t1).*cos(t2)-sin(t1).*sin(t2)));
et22 = -t1_d.*(t1_d.*(L2.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))+L1.*cos(t1))+L2.*t2_d.*(cos(t1).*cos(t2)-sin(t1).*sin(t2)))+q1_dd.*(et18+et19)+Xc_d.*q1_d.*sin(q1).*1.0-L2.*t2_dd.*(cos(t1).*sin(t2)+cos(t2).*sin(t1));
AEQP2 = [et20+et21+et22;et9+et10+et11;X_dd+X1_dd.*cos(q1)-q1_d.*(X1_d.*sin(q1)+X1.*q1_d.*cos(q1))-X1.*q1_dd.*sin(q1)-X1_d.*q1_d.*sin(q1);Y_dd+X1_dd.*sin(q1)+q1_d.*(X1_d.*cos(q1)-X1.*q1_d.*sin(q1))+X1.*q1_dd.*cos(q1)+X1_d.*q1_d.*cos(q1)];
end
