function Dampo = R_dampo(Mo,X_d,Xo,Y_d,q1,q1_d)
%R_dampo
%    Dampo = R_dampo(Mo,X_d,Xo,Y_d,Q1,Q1_D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:08

Dampo = [-Mo.*Xo.*q1_d.^2.*cos(q1);-Mo.*Xo.*q1_d.^2.*sin(q1);-q1_d.*(Mo.*Xo.*cos(q1).*(X_d-Xo.*q1_d.*sin(q1))+Mo.*Xo.*sin(q1).*(Y_d+Xo.*q1_d.*cos(q1)))+Mo.*Xo.*q1_d.*cos(q1).*(X_d-Xo.*q1_d.*sin(q1))+Mo.*Xo.*q1_d.*sin(q1).*(Y_d+Xo.*q1_d.*cos(q1))];
end
