function out1 = R_EQP(L01,L1,L2,X,Xc,Xo,Y,Yo,q1,r,t1,t2)
%R_EQP
%    OUT1 = R_EQP(L01,L1,L2,X,Xc,Xo,Y,Yo,Q1,R,T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:08

et1 = cos(q1).*1.0;
et2 = sin(q1).*6.123233995736766e-17;
et3 = L01-Y+L2.*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+r.*(cos(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+sin(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*cos(t2)-sin(t1).*sin(t2)))-Yo.*(cos(q1)+sin(q1).*6.123233995736766e-17)-Yo.*(et1+et2)+L1.*sin(t1);
et4 = Xc.*sin(q1).*(-1.0)-Xo.*sin(q1);
et5 = cos(q1).*6.123233995736766e-17;
et6 = sin(q1).*(-1.0);
et7 = -X+L2.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))+r.*(cos(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*cos(t2)-sin(t1).*sin(t2))-sin(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*sin(t2)+cos(t2).*sin(t1)))+L1.*cos(t1)-Yo.*(et5+et6);
et8 = Xc.*cos(q1).*(-1.0)-Xo.*cos(q1);
et9 = -Yo.*(cos(q1).*6.123233995736766e-17-sin(q1));
out1 = [et7+et8+et9;et3+et4];
end
