function out1 = R_EQ2(C1,C2,I1,I2,L1,M1,M2,T1,T2,g,t1,t2,t1_d,t2_d)
%R_EQ2
%    OUT1 = R_EQ2(C1,C2,I1,I2,L1,M1,M2,T1,T2,G,t1,t2,T1_D,T2_D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:09

et1 = -((I2+C2.^2.*M2+C2.*L1.*M2.*cos(t2)).*(T1+t2_d.*(C2.*L1.*M2.*t1_d.*sin(t2).*2.0+C2.*L1.*M2.*t2_d.*sin(t2))-M2.*g.*(C2.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))+L1.*cos(t1))-C1.*M1.*g.*cos(t1)))./(I1.*I2+C2.^2.*L1.^2.*M2.^2+C1.^2.*I2.*M1+C2.^2.*I1.*M2+I2.*L1.^2.*M2+C1.^2.*C2.^2.*M1.*M2-C2.^2.*L1.^2.*M2.^2.*cos(t2).^2);
et2 = -((-T2+C2.*M2.*g.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))+C2.*L1.*M2.*t1_d.^2.*sin(t2)).*(I1+I2+C1.^2.*M1+C2.^2.*M2+L1.^2.*M2+C2.*L1.*M2.*cos(t2).*2.0))./(I1.*I2+C2.^2.*L1.^2.*M2.^2+C1.^2.*I2.*M1+C2.^2.*I1.*M2+I2.*L1.^2.*M2+C1.^2.*C2.^2.*M1.*M2-C2.^2.*L1.^2.*M2.^2.*cos(t2).^2);
out1 = et1+et2;
end
