function EQ = R_EQ1(L01,L1,L2,r,t1,t2)
%R_EQ1
%    EQ = R_EQ1(L01,L1,L2,R,T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    30-Aug-2024 05:32:21

EQ = [L2.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))+L1.*cos(t1)+r.*(cos(t1+t2+pi./2.0).*(cos(t1).*cos(t2)-sin(t1).*sin(t2))+sin(t1+t2+pi./2.0).*(cos(t1).*sin(t2)+cos(t2).*sin(t1)));L01+L2.*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+L1.*sin(t1)+r.*(cos(t1+t2+pi./2.0).*(cos(t1).*sin(t2)+cos(t2).*sin(t1))-sin(t1+t2+pi./2.0).*(cos(t1).*cos(t2)-sin(t1).*sin(t2)))];
end
