function EQ = R_EQ(L01,L1,L2,q1,r,t1,t2)
%R_EQ
%    EQ = R_EQ(L01,L1,L2,Q1,R,T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:05

EQ = [L2.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))+r.*(cos(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*cos(t2)-sin(t1).*sin(t2))-sin(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*sin(t2)+cos(t2).*sin(t1)))+L1.*cos(t1);L01+L2.*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+r.*(cos(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+sin(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*cos(t2)-sin(t1).*sin(t2)))+L1.*sin(t1)];
end
