function out1 = R_EQO(X,Xc,Xo,Y,Yo,q1)
%R_EQO
%    OUT1 = R_EQO(X,Xc,Xo,Y,Yo,Q1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:07

et1 = cos(q1).*1.0;
et2 = sin(q1).*6.123233995736766e-17;
et3 = Y+Yo.*(cos(q1)+sin(q1).*6.123233995736766e-17)+Yo.*(et1+et2)+Xc.*sin(q1).*1.0;
et4 = Xo.*sin(q1);
et5 = cos(q1).*6.123233995736766e-17;
et6 = sin(q1).*(-1.0);
et7 = X+Yo.*(et5+et6)+Xc.*cos(q1).*1.0+Xo.*cos(q1);
et8 = Yo.*(cos(q1).*6.123233995736766e-17-sin(q1));
out1 = [et7+et8;et3+et4];
end
