function EQ = R_FC(Xc,Yo,mu,q1)
%R_FC
%    EQ = R_FC(Xc,Yo,MU,Q1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    19-Sep-2024 17:55:18

EQ = abs(acos(1.0./sqrt(abs((Yo.*sin(q1-pi./2.0).*2.0)./tan(q1-pi./2.0)-(Xc.*sin(q1))./tan(q1)).^2+abs(tan(q1).*((Xc.*sin(q1))./tan(q1)-(Yo.*sin(q1-pi./2.0).*2.0)./tan(q1))).^2).*(tan(q1).*((Xc.*sin(q1))./tan(q1)-(Yo.*sin(q1-pi./2.0).*2.0)./tan(q1)).^2+tan(q1).*((Xc.*sin(q1))./tan(q1)-(Yo.*sin(q1-pi./2.0).*2.0)./tan(q1)).*((Yo.*sin(q1-pi./2.0).*2.0)./tan(q1-pi./2.0)-(Xc.*sin(q1))./tan(q1)))))-atan(mu);
end
