function Grao = R_Grao(Mo,Xo,g,q1)
%R_Grao
%    Grao = R_Grao(Mo,Xo,G,Q1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:08

Grao = [0.0;Mo.*g;Mo.*Xo.*g.*cos(q1)];
end
