function Gra = R_Gra(C1,C2,L1,M1,M2,g,t1,t2)
%R_Gra
%    Gra = R_Gra(C1,C2,L1,M1,M2,G,T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:08

Gra = [M2.*g.*(C2.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))+L1.*cos(t1))+C1.*M1.*g.*cos(t1);C2.*M2.*g.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))];
end
