function out1 = R_Grasp(Xc,Yo,q1)
%R_Grasp
%    OUT1 = R_Grasp(Xc,Yo,Q1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:07

et1 = cos(q1).*1.0;
et2 = sin(q1).*6.123233995736766e-17;
et3 = cos(q1).*6.123233995736766e-17;
et4 = sin(q1).*(-1.0);
mt1 = [1.0,0.0,Xc.*sin(q1).*(-1.0)-Yo.*(et1+et2),0.0,1.0];
mt2 = [Xc.*cos(q1).*1.0+Yo.*(et3+et4)];
out1 = reshape([mt1,mt2],3,2);
end
