function JacO2 = R_JacO2
%R_JacO2
%    JacO2 = R_JacO2

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:07

JacO2 = reshape([-1.0,0.0,1.0,0.0,0.0,-1.0,0.0,1.0],[4,2]);
end
