function JacFd2 = R_JacFd2(L1,L2,X1,X1_d,Xc,Xo,Yo,q1,q1_d,r,t1,t2,t1_d,t2_d)
%R_JacFd2
%    JacFd2 = R_JacFd2(L1,L2,X1,X1_d,Xc,Xo,Yo,Q1,Q1_D,R,T1,T2,T1_D,T2_D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:07

et1 = cos(q1).*1.0;
et2 = sin(q1).*6.123233995736766e-17;
et3 = -r.*(cos(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+sin(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*cos(t2)-sin(t1).*sin(t2)))+Yo.*(cos(q1)+sin(q1).*6.123233995736766e-17)+Yo.*(et1+et2);
et4 = Xc.*sin(q1).*1.0+Xo.*sin(q1);
et5 = cos(q1).*6.123233995736766e-17;
et6 = sin(q1).*(-1.0);
et7 = -r.*(cos(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*cos(t2)-sin(t1).*sin(t2))-sin(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*sin(t2)+cos(t2).*sin(t1)))+Yo.*(et5+et6);
et8 = Xc.*cos(q1).*1.0+Xo.*cos(q1)+Yo.*(cos(q1).*6.123233995736766e-17-sin(q1));
JacFd2 = reshape([-t1_d.*(L2.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))+L1.*cos(t1))-L2.*t2_d.*(cos(t1).*cos(t2)-sin(t1).*sin(t2)),-t1_d.*(L2.*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+L1.*sin(t1))-L2.*t2_d.*(cos(t1).*sin(t2)+cos(t2).*sin(t1)),0.0,0.0,-L2.*t1_d.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))-L2.*t2_d.*(cos(t1).*cos(t2)-sin(t1).*sin(t2)),-L2.*t1_d.*(cos(t1).*sin(t2)+cos(t2).*sin(t1))-L2.*t2_d.*(cos(t1).*sin(t2)+cos(t2).*sin(t1)),0.0,0.0,q1_d.*(et7+et8),q1_d.*(et3+et4),-X1_d.*sin(q1)-X1.*q1_d.*cos(q1),X1_d.*cos(q1)-X1.*q1_d.*sin(q1),0.0,0.0,-q1_d.*sin(q1),q1_d.*cos(q1)],[4,4]);
end
