function JacOd = R_JacOd(Xc,Xo,Yo,q1,q1_d,r,t1,t2)
%R_JacOd
%    JacOd = R_JacOd(Xc,Xo,Yo,Q1,Q1_D,R,T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:08

et1 = cos(q1).*1.0;
et2 = sin(q1).*6.123233995736766e-17;
et3 = -r.*(cos(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+sin(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*cos(t2)-sin(t1).*sin(t2)))+Yo.*(cos(q1)+sin(q1).*6.123233995736766e-17)+Yo.*(et1+et2);
et4 = Xc.*sin(q1).*1.0+Xo.*sin(q1);
et5 = cos(q1).*6.123233995736766e-17;
et6 = sin(q1).*(-1.0);
et7 = -r.*(cos(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*cos(t2)-sin(t1).*sin(t2))-sin(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*sin(t2)+cos(t2).*sin(t1)))+Yo.*(et5+et6);
et8 = Xc.*cos(q1).*1.0+Xo.*cos(q1)+Yo.*(cos(q1).*6.123233995736766e-17-sin(q1));
JacOd = reshape([q1_d.*(et7+et8),q1_d.*(et3+et4),0.0,0.0,0.0,0.0],[2,3]);
end
