function JacF2 = R_JacF2(L1,L2,X1,Xc,Xo,Yo,q1,r,t1,t2)
%R_JacF2
%    JacF2 = R_JacF2(L1,L2,X1,Xc,Xo,Yo,Q1,R,T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:07

et1 = cos(q1).*6.123233995736766e-17;
et2 = sin(q1).*(-1.0);
et3 = r.*(cos(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*cos(t2)-sin(t1).*sin(t2))-sin(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*sin(t2)+cos(t2).*sin(t1)))-Yo.*(et1+et2);
et4 = Xc.*cos(q1).*(-1.0)-Xo.*cos(q1);
et5 = -Yo.*(cos(q1).*6.123233995736766e-17-sin(q1));
et6 = cos(q1).*1.0;
et7 = sin(q1).*6.123233995736766e-17;
et8 = -r.*(cos(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+sin(q1-t1-t2+pi.*(3.0./2.0)).*(cos(t1).*cos(t2)-sin(t1).*sin(t2)))+Yo.*(cos(q1)+sin(q1).*6.123233995736766e-17)+Yo.*(et6+et7);
et9 = Xc.*sin(q1).*1.0+Xo.*sin(q1);
JacF2 = reshape([-L2.*(cos(t1).*sin(t2)+cos(t2).*sin(t1))-L1.*sin(t1),L2.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))+L1.*cos(t1),0.0,0.0,-L2.*(cos(t1).*sin(t2)+cos(t2).*sin(t1)),L2.*(cos(t1).*cos(t2)-sin(t1).*sin(t2)),0.0,0.0,et8+et9,et3+et4+et5,-X1.*sin(q1),X1.*cos(q1),0.0,0.0,cos(q1),sin(q1)],[4,4]);
end
