function Jac_d = R_Jd(L1,L2,t1,t2,t1_d,t2_d)
%R_Jd
%    Jac_d = R_Jd(L1,L2,T1,T2,T1_D,T2_D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:06

Jac_d = reshape([-t1_d.*(L2.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))+L1.*cos(t1))-L2.*t2_d.*(cos(t1).*cos(t2)-sin(t1).*sin(t2)),-t1_d.*(L2.*(cos(t1).*sin(t2)+cos(t2).*sin(t1))+L1.*sin(t1))-L2.*t2_d.*(cos(t1).*sin(t2)+cos(t2).*sin(t1)),-L2.*t1_d.*(cos(t1).*cos(t2)-sin(t1).*sin(t2))-L2.*t2_d.*(cos(t1).*cos(t2)-sin(t1).*sin(t2)),-L2.*t1_d.*(cos(t1).*sin(t2)+cos(t2).*sin(t1))-L2.*t2_d.*(cos(t1).*sin(t2)+cos(t2).*sin(t1))],[2,2]);
end
