function [A0,A1,A2] = R_Kp_(kp1,kp2,kp3,t0,t1,t2)
%R_Kp
%    OUT1 = R_Kp(KP1,KP2,KP3,T0,T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    01-Oct-2023 22:48:58

AA = [-(kp1.*t1.*t2.^2-kp1.*t1.^2.*t2-kp2.*t0.*t2.^2+kp2.*t0.^2.*t2+kp3.*t0.*t1.^2-kp3.*t0.^2.*t1)./((t0-t1).*(t0.*t1-t0.*t2-t1.*t2+t2.^2)),-(kp1.*t1.^2-kp2.*t0.^2-kp1.*t2.^2+kp3.*t0.^2+kp2.*t2.^2-kp3.*t1.^2)./((t0-t1).*(t0.*t1-t0.*t2-t1.*t2+t2.^2)),(kp1.*t1-kp2.*t0-kp1.*t2+kp3.*t0+kp2.*t2-kp3.*t1)./((t0-t1).*(t0.*t1-t0.*t2-t1.*t2+t2.^2))];
A0=AA(1);
A1=AA(2);
A2=AA(3);
end
