function Mass = R_M(C1,C2,I1,I2,L1,M1,M2,t2)
%R_M
%    Mass = R_M(C1,C2,I1,I2,L1,M1,M2,T2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:08

Mass = reshape([I1+I2+C1.^2.*M1+C2.^2.*M2+L1.^2.*M2+C2.*L1.*M2.*cos(t2).*2.0,I2+C2.^2.*M2+C2.*L1.*M2.*cos(t2),I2+C2.^2.*M2+C2.*L1.*M2.*cos(t2),I2+C2.^2.*M2],[2,2]);
end
