function Masso = R_Mo(Io,Mo,Xo,q1)
%R_Mo
%    Masso = R_Mo(Io,Mo,Xo,Q1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:08

Masso = reshape([Mo,0.0,-Mo.*Xo.*sin(q1),0.0,Mo,Mo.*Xo.*cos(q1),-Mo.*Xo.*sin(q1),Mo.*Xo.*cos(q1),Io+Mo.*Xo.^2.*cos(q1).^2+Mo.*Xo.^2.*sin(q1).^2],[3,3]);
end
