function To = R_Object_Dynamics(Io,Mo,X_d,X_dd,Xo,Y_d,Y_dd,g,q1,q1_d,q1_dd)
%R_Object_Dynamics
%    To = R_Object_Dynamics(Io,Mo,X_d,X_dd,Xo,Y_d,Y_dd,G,Q1,Q1_D,Q1_DD)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:08

To = [Mo.*X_dd-Mo.*Xo.*q1_dd.*sin(q1)-Mo.*Xo.*q1_d.^2.*cos(q1);Mo.*Y_dd+Mo.*g+Mo.*Xo.*q1_dd.*cos(q1)-Mo.*Xo.*q1_d.^2.*sin(q1);-q1_d.*(Mo.*Xo.*cos(q1).*(X_d-Xo.*q1_d.*sin(q1))+Mo.*Xo.*sin(q1).*(Y_d+Xo.*q1_d.*cos(q1)))+q1_dd.*(Io+Mo.*Xo.^2.*cos(q1).^2+Mo.*Xo.^2.*sin(q1).^2)+Mo.*Xo.*Y_dd.*cos(q1)+Mo.*Xo.*g.*cos(q1)-Mo.*X_dd.*Xo.*sin(q1)+Mo.*Xo.*q1_d.*cos(q1).*(X_d-Xo.*q1_d.*sin(q1))+Mo.*Xo.*q1_d.*sin(q1).*(Y_d+Xo.*q1_d.*cos(q1))];
end
