function out1 = R_PCM(X,Xo,Y,Yo,q1)
%R_PCM
%    OUT1 = R_PCM(X,Xo,Y,Yo,Q1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:06

out1 = [X+Xo.*cos(q1)+Yo.*(cos(q1).*6.123233995736766e-17-sin(q1));Y+Yo.*(cos(q1)+sin(q1).*6.123233995736766e-17)+Xo.*sin(q1)];
end
