function Vco = R_Vco(X_d,Xc,Xo,Y_d,Yo,q1,q1_d)
%R_Vco
%    Vco = R_Vco(X_d,Xc,Xo,Y_d,Yo,Q1,Q1_D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:07

et1 = cos(q1).*6.123233995736766e-17;
et2 = sin(q1).*(-1.0);
et3 = Yo.*(et1+et2)+Xc.*cos(q1).*1.0+Xo.*cos(q1);
et4 = Yo.*(cos(q1).*6.123233995736766e-17-sin(q1));
et5 = cos(q1).*1.0;
et6 = sin(q1).*6.123233995736766e-17;
et7 = Yo.*(cos(q1)+sin(q1).*6.123233995736766e-17)+Yo.*(et5+et6)+Xc.*sin(q1).*1.0;
et8 = Xo.*sin(q1);
Vco = [X_d-q1_d.*(et7+et8);Y_d+q1_d.*(et3+et4)];
end
