function V_CM = R_VCM(X_d,Xo,Y_d,Yo,q1,q1_d)
%R_VCM
%    V_CM = R_VCM(X_d,Xo,Y_d,Yo,Q1,Q1_D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:06

V_CM = [X_d-q1_d.*(Yo.*(cos(q1)+sin(q1).*6.123233995736766e-17)+Xo.*sin(q1));Y_d+q1_d.*(Xo.*cos(q1)+Yo.*(cos(q1).*6.123233995736766e-17-sin(q1)))];
end
