function X_d = R_Xd(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,t)
%R_Xd
%    X_d = R_Xd(A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Sep-2023 12:07:26

X_d = a1+a2.*t.*2.0+a3.*t.^2.*3.0+a4.*t.^3.*4.0+a5.*t.^4.*5.0+a6.*t.^5.*6.0+a7.*t.^6.*7.0+a8.*t.^7.*8.0+a9.*t.^8.*9.0+a10.*t.^9.*1.0e+1+a11.*t.^10.*1.1e+1;
end
