function X_dd = R_Xdd(a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,t)
%R_Xdd
%    X_dd = R_Xdd(A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Sep-2023 12:07:27

X_dd = a2.*2.0+a3.*t.*6.0+a4.*t.^2.*1.2e+1+a5.*t.^3.*2.0e+1+a6.*t.^4.*3.0e+1+a7.*t.^5.*4.2e+1+a8.*t.^6.*5.6e+1+a9.*t.^7.*7.2e+1+a10.*t.^8.*9.0e+1+a11.*t.^9.*1.1e+2;
end
