function Cf = RCf(C2,L1,M2,t2,t1_d,t2_d)
%RCf
%    Cf = RCf(C2,L1,M2,T2,T1_D,T2_D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Sep-2024 12:43:09

Cf = reshape([-C2.*L1.*M2.*t2_d.*sin(t2),C2.*L1.*M2.*t1_d.*sin(t2),-C2.*L1.*M2.*t1_d.*sin(t2)-C2.*L1.*M2.*t2_d.*sin(t2),0.0],[2,2]);
end
