function out1 = RFs(C1,C2,D1,D2,K1,K2,M1,M2,Xa,Xa_d,Xd,Xd_d,Xd_dd,Ya,Ya_d,Yd,Yd_d,Yd_dd,a1,a2,g,m1,m2,m3,mo,mu,mus,q1,q2)
%RFs
%    OUT1 = RFs(C1,C2,D1,D2,K1,K2,M1,M2,Xa,Xa_d,Xd,Xd_d,Xd_dd,Ya,Ya_d,Yd,Yd_d,Yd_dd,A1,A2,G,m1,m2,M3,MO,MU,MUS,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-Jul-2024 13:04:53

mt1 = [(M1.*Xd_dd+M2.*Yd_dd+D1.*(Xa_d-Xd_d)+D2.*(Ya_d-Yd_d)+K1.*(Xa-Xd)+K2.*(Ya-Yd)+g.*mo.*mu+((cos(q1).*cos(q2)-sin(q1).*sin(q2)).*(mu+1.0).*(g.*(C2.*(cos(q1).*cos(q2)-sin(q1).*sin(q2))+a1.*cos(q1)).*(m2+m3)+C1.*g.*m1.*cos(q1)))./(a1.*cos(q1).^2.*sin(q2)+a1.*sin(q1).^2.*sin(q2))-(C2.*g.*(m2+m3).*(cos(q1).*cos(q2)-sin(q1).*sin(q2)).*(mu+1.0).*(a1.*cos(q1)+a2.*cos(q1).*cos(q2)-a2.*sin(q1).*sin(q2)))./(a1.*a2.*cos(q1).^2.*sin(q2)+a1.*a2.*sin(q1).^2.*sin(q2)))./(mu+1.0)];
mt2 = [(M1.*Xd_dd+M2.*Yd_dd+D1.*(Xa_d-Xd_d)+D2.*(Ya_d-Yd_d)+K1.*(Xa-Xd)+K2.*(Ya-Yd)+g.*mo.*mu+((cos(q1).*cos(q2)-sin(q1).*sin(q2)).*(mu+1.0).*(g.*(C2.*(cos(q1).*cos(q2)-sin(q1).*sin(q2))+a1.*cos(q1)).*(m2+m3)+C1.*g.*m1.*cos(q1)))./(a1.*cos(q1).^2.*sin(q2)+a1.*sin(q1).^2.*sin(q2))-(C2.*g.*(m2+m3).*(cos(q1).*cos(q2)-sin(q1).*sin(q2)).*(mu+1.0).*(a1.*cos(q1)+a2.*cos(q1).*cos(q2)-a2.*sin(q1).*sin(q2)))./(a1.*a2.*cos(q1).^2.*sin(q2)+a1.*a2.*sin(q1).^2.*sin(q2)))./(mus.*(mu+1.0))];
out1 = [mt1;mt2];
end
